### ISSUE TITLE
Disable Captcha not working

### ISSUE THREAD

**Issue by webdevilopers** [mremi/ContactBundle#18]
I followed the config in issue https://github.com/mremi/ContactBundle/issues/7:

``` yml
  mremi_contact:
    form:
        captcha_disabled:  true
        captcha_type:      genemu_captcha
```

Still the Captcha appears in `dev`.

Checking `$this->captchaDisabled` in
https://github.com/mremi/ContactBundle/blob/master/Form/Type/ContactType.php#L91
returns `false` via `VarDumper`.

The last time I worked on the project it seemed to work. I recently updated to Symfony **2.6** - mabye it has changed since this update.

**Comment by webdevilopers** [comment]
Sorry for the late response @mremi . Havn't been working on the project for a long time.

With current `dev-master` I use this service to override the bundle:
```xml
        <service id="sps_web.contact_request_form_type" class="Sps\Bundle\ContactUsBundle\Form\ContactRequestType">
            <tag name="form.type" alias="contact_request_form" />
            <argument type="service" id="mremi_contact.subject_provider.noop"></argument>
            <argument>Sps\Bundle\ContactUsBundle\Entity\ContactRequest</argument>
            <argument>genemu_captcha</argument>
        </service>
```

I've seen some other issues so far:
- https://github.com/mremi/ContactBundle/pull/21
- https://github.com/genemu/GenemuFormBundle/issues/181

The `captcha_disabled` was removed I think.

What is the best way to disable the captcha for `dev` now?

Should I use `config_dev` and `config_prod` and configure both keys `genemu_form` and `mremi_contact` there? Do we have an example in the docs?

**Comment by mremi** [comment]
Hi @webdevilopers !

Yep, `captcha_disabled` has been removed: if you don't fill the `captcha_type` node, no captcha will be added to the form. So if you want to disable the captcha for the `dev` env (ie enable it only for `prod`), you have to use the `config*.yml` files like this for instance:

```yaml
# app/config/config.yml used for common configs for all env
mremi_contact:
    form:
        type: contact_request_form

    email:
        to: webmaster@example.com
```

```yaml
# app/config/config_prod.yml
mremi_contact:
    form:
        captcha_type: genemu_captcha
```

**Comment by webdevilopers** [comment]
Thanks for the hint @mremi . I tried your config and passed an empty 3rd argument via service since I need my custom form:

```php
        <service id="sps_web.contact_request_form_type" class="Sps\Bundle\ContactUsBundle\Form\ContactRequestType">
            <tag name="form.type" alias="contact_request_form" />
            <argument type="service" id="mremi_contact.subject_provider.noop"></argument>
            <argument>Sps\Bundle\ContactUsBundle\Entity\ContactRequest</argument>
            <argument>genemu_captcha</argument>
        </service>
```

Unfortunately no captcha shows up. I guess I have to pass the parameter from the config as 3rd argument?

**Comment by mremi** [comment]
Yep or `CaptchaType::class` if you are using Symfony 2.8+ (with PHP 5.5+, else `Genemu\Bundle\FormBundle\Form\Core\Type\CaptchaType`).
I guess you extend the base type of this bundle, if not and if you are the final user of this service, you don't need to inject these arguments, use them as it in the service, more simple.

**Comment by webdevilopers** [comment]
Could you give an example of how to get my custom form working without injecting? Because
```xml
        <service id="sps_web.contact_request_form_type" class="Sps\Bundle\ContactUsBundle\Form\ContactRequestType">
            <tag name="form.type" alias="contact_request_form" />
<!--            <argument type="service" id="mremi_contact.subject_provider.noop"></argument>
            <argument>Sps\Bundle\ContactUsBundle\Entity\ContactRequest</argument>
            <argument>%mremi_contact.form.captcha_type%</argument>-->
        </service>
```

causes the constructor to fail:
**Argument 1 passed to Mremi\ContactBundle\Form\Type\ContactType::__construct() must be an instance of Mremi\ContactBundle\Provider\SubjectProviderInterface, none given**

My config for `dev`:
```yaml
mremi_contact:
    store_data:            true
#    contact_class:         Mremi\ContactBundle\Model\Contact
    contact_class:         Sps\Bundle\ContactUsBundle\Entity\ContactRequest

    form:
        type:              contact_request_form
        name:              contact_form
        validation_groups: [ContactRequest]
#        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
#        captcha_type:      false
```

Thanks in advance @mremi !
