### ISSUE TITLE
N'est il pas possible de surcharger l'émetteur du mail ?

### ISSUE THREAD

**Issue by pkshetlie** [mremi/ContactBundle#22]
Bonjour, 
à priori il n’est pas possible pour le moment de surcharger l’émetteur du mail, ce qui est dommage dans mon cas, car je ne peux pas permettre à n'importe quelle adresse mail d'envoyer un mail sur mon serveur il me faut utiliser une adresse mail spéciale. Sinon a part ça le Bundle est top. Bravo.

Serait il possible de prévoir cette surcharge dans le config.yml pour une prochaine évolution?
Cordialement.
Désolé je préfère ne pas traduire ma demande pour qu'elle reste claire.

**Comment by mremi** [comment]
Bonjour,

Tout d'abord merci !

Effectivement, pour l'instant ce sont les informations saisies dans le formulaire qui sont utilisées.
On pourrait imaginer ajouter un noeud dans la configuration :

```yaml
mremi_contact:
    email:
        from: 
            - { address: john.doe@example.com, name: "John Doe" }
            - { address: foo.bar@example.com }
```

avec `address` mandatory et `name` facultatif.

Si cette configuration est présente, elle serait utilisée, sinon c'est la logique déjà en place.
Qu'en pensez-vous ?
