### ISSUE TITLE
I don't understand why it don't use swiftmailer

### ISSUE THREAD

**Issue by pkshetlie** [mremi/ContactBundle#27]
```yml
#config.yml

mremi_contact:
    store_data:            false
    contact_class:         Mremi\ContactBundle\Model\Contact

    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
        captcha_type:      captcha
    email:
        mailer:            mremi_contact.mailer.twig_swift
        from:
            - { address: website@example.fr, name: "Contact depuis le site" }
        to:
            - { address: user@example.fr, name: "Administrateur" }
        template:          MremiContactBundle:Contact:email.txt.twig

# Swiftmailer Configuration
swiftmailer:
    sender_address: website@example.com
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
```

any suggestion ?
