### ISSUE TITLE
Surcharger Type pour enlever un champ

### ISSUE THREAD

**Issue by razbounak** [mremi/ContactBundle#43]
Hi remi, je I would like remove the fields "title" of your bundle in override the Type but it doesn't works and I'm blocked since few days

```yaml
# app/config/config.yml
mremi_contact:
    store_data:            false
    contact_class:         Mremi\ContactBundle\Model\Contact

    form:
        type:              mb_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop

    email:
        mailer:            mremi_contact.mailer.twig_swift
        from:              [ address: thomas@nnn.nnn]
        to:                [ address: thomas@nnn.nnn]
        template:          MremiContactBundle:Contact:email.txt.twig
```

```php
// src/MB/ContactBundle/MBContactBundle

<?php

namespace MB\ContactBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class MBContactBundle extends Bundle
{
    public function getParent()
    {
        return 'MremiContactBundle';
    }
}
```

```php
// src/MB/ContactBundle/Form/Type/ContactType.php

<?php

namespace MB\ContactBundle\Form\Type;

use Mremi\ContactBundle\Form\Type\ContactType as ContactTypeMremi;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ContactType extends ContactTypeMremi
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder->remove('title');
    }

    public function getName()
    {
        return 'mb_contact';
    }
}
```

Thank you for helping me !
